name: Deploy Frontend Application

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Deploy to production
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}     
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          debug: true # Enable debug mode for the SSH action
          script: |
            cd /home/ubuntu/apps/frontend/fitscheck-website
            git pull origin main
            npm ci
            npm run build
            pm2 restart frontend
